[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spin = "0.9.3"
x86_64 = "0.14.9"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]