[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
ps2-mouse = "0.1.3"
spin = "0.9.3"
spinning_top = "0.3.0"
multiboot2 = "0.13.3"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]